@startuml
|Nhân viên|
start
:Nhập thông tin sách;
|Hệ thống|
:Kiểm tra chất lượng;

if (Sách đạt yêu cầu?) then (Có)
  :Đưa vào kho;
  :Cập nhật tồn kho;
else (Không)
  :Đánh dấu sách lỗi;
endif

|Nhân viên|
:Kiểm kê định kỳ;
|Hệ thống|
:Đối chiếu số lượng;
if (Sai lệch?) then (Có)
  |Nhân viên|
  :Điều chỉnh dữ liệu;
endif
|Hệ thống|
:Phân tích bán chạy;
|Nhân viên|
:Đề xuất nhập thêm / thanh lý sách;
stop
@enduml
