@startuml

|Khách hàng|

start
:Chọn sách, gửi đơn hàng;

|Nhân viên|
:Tiếp nhận và kiểm tra;
if (Còn hàng?) then (Có)
  :Tạo hóa đơn;
  |Khách hàng|
  :Thanh toán;
  |Nhân viên|
  :Kiểm tra, đóng gói;
  |Hệ thống|
  :Cập nhật đơn hàng;
  :Cập nhật kho;
  |Nhân viên|
  if (Đơn online?) then (Có)
    :Vận chuyển;
  else (Không)
    :Giao trực tiếp;
  endif
else (Không)
  :Thông báo hết hàng;
endif
stop
@enduml
